/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity.schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Photo = {
  asset?: SanityImageAssetReference;
  media?: unknown // Unable to locate the referenced type "photo.media" in schema
;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type ContentBlock = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "script";
  listItem?: never;
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  } | {
    reference?: PageReference;
    _type: "internalLink";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  _key: string;
} & GalleryBlock | {
  _key: string;
} & SponsorGridBlock>;

export type SponsorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sponsor";
};

export type SponsorGridBlock = {
  _type: "sponsorGridBlock";
  pick?: Array<{
    _key: string;
  } & SponsorReference>;
};

export type GalleryBlock = {
  _type: "galleryBlock";
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
};

export type PageBuilder = Array<{
  _key: string;
} & Hero | {
  _key: string;
} & Events | {
  _key: string;
} & Team | {
  _key: string;
} & Content | {
  _key: string;
} & HomeHero | {
  _key: string;
} & HomeMission | {
  _key: string;
} & HomeImpact | {
  _key: string;
} & HomeEvents | {
  _key: string;
} & HomeSupport | {
  _key: string;
} & HomeContent>;

export type HomeContent = {
  _type: "homeContent";
  title?: string;
  content?: ContentBlock;
  color?: "red" | "yellow" | "blue" | "grey";
};

export type HomeSupport = {
  _type: "homeSupport";
  title?: string;
  content?: ContentBlock;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  color?: "red" | "yellow" | "blue" | "grey";
};

export type HomeEvents = {
  _type: "homeEvents";
  title?: string;
  noOfEvents?: number;
  viewMore?: string;
  color?: "red" | "yellow" | "blue" | "grey";
};

export type HomeImpact = {
  _type: "homeImpact";
  title?: string;
  statistics?: Array<{
    number?: string;
    label?: string;
    _type: "homeImpactStatistic";
    _key: string;
  }>;
  color?: "red" | "yellow" | "blue" | "grey";
};

export type HomeMission = {
  _type: "homeMission";
  title?: string;
  content?: ContentBlock;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  color?: "red" | "yellow" | "blue" | "grey";
};

export type HomeHero = {
  _type: "homeHero";
  title?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    _type: "image";
  };
  buttons?: Array<{
    label?: string;
    isPrimary?: boolean;
    link?: PageReference;
    _type: "homeHeroButton";
    _key: string;
  }>;
};

export type Content = {
  _type: "content";
  content?: ContentBlock;
  color?: "red" | "yellow" | "blue" | "grey";
};

export type Team = {
  _type: "team";
  title?: string;
  members?: Array<{
    name?: string;
    role?: string;
    photo?: Photo;
    bio?: string;
    github?: string;
    website?: string;
    _type: "teamMember";
    _key: string;
  }>;
  color?: "red" | "yellow" | "blue" | "grey";
};

export type Events = {
  _type: "events";
  color?: "red" | "yellow" | "blue" | "grey";
};

export type Hero = {
  _type: "hero";
  subtitle?: string;
  title?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    _type: "image";
  };
  color?: "red" | "yellow" | "blue" | "grey";
  transparent?: boolean;
};

export type Seo = {
  _type: "seo";
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Footer = {
  _type: "footer";
  sitemapTitle?: string;
  sitemap?: Array<{
    label?: string;
    link?: PageReference;
    _type: "footerLink";
    _key: string;
  }>;
  socialsTitle?: string;
  socials?: Array<string>;
  contactTitle?: string;
  contact?: Array<{
    label?: string;
    email?: string;
    _type: "footerContact";
    _key: string;
  }>;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tagline?: string;
  copyright?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Navbar = {
  _type: "navbar";
  logo?: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  links?: Array<{
    label?: string;
    link?: PageReference;
    _type: "navbarLink";
    _key: string;
  }>;
};

export type NotFoundPage = {
  _id: string;
  _type: "notFoundPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subtitle?: string;
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  backButtonLabel?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  indexPage?: PageReference;
  navbar?: Navbar;
  footer?: Footer;
  globalSeo?: {
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  startDate?: string;
  logo?: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  cover?: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  sections?: PageBuilder;
  seo?: Seo;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: PageBuilder;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Sponsor = {
  _id: string;
  _type: "sponsor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SanityImageAssetReference | Photo | PageReference | ContentBlock | SponsorReference | SponsorGridBlock | GalleryBlock | PageBuilder | HomeContent | HomeSupport | HomeEvents | HomeImpact | HomeMission | HomeHero | Content | Team | Events | Hero | Seo | Footer | Navbar | NotFoundPage | SanityImageCrop | SanityImageHotspot | SiteSettings | Event | Page | Slug | Sponsor | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../src/lib/internalLink.ts
// Variable: INTERNAL_LINK_QUERY
// Query: *[_type == "page" && _id == $id][0] { slug }
export type INTERNAL_LINK_QUERY_RESULT = {
  slug: Slug | null;
} | null;

// Source: ../src/queries/index.ts
// Variable: INDEX_QUERY
// Query: *[_type == "siteSettings"][0] {  indexPage->}
export type INDEX_QUERY_RESULT = {
  indexPage: {
    _id: string;
    _type: "page";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    sections?: PageBuilder;
    seo?: Seo;
  } | null;
} | null;

// Source: ../src/queries/index.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]
export type PAGE_QUERY_RESULT = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  sections?: PageBuilder;
  seo?: Seo;
} | null;

// Source: ../src/queries/index.ts
// Variable: EVENT_PAGE_QUERY
// Query: *[_type == "event" && slug.current == $slug][0]
export type EVENT_PAGE_QUERY_RESULT = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  startDate?: string;
  logo?: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  cover?: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  sections?: PageBuilder;
  seo?: Seo;
} | null;

// Source: ../src/queries/index.ts
// Variable: SPONSORS_QUERY
// Query: *[_type == "sponsor"] | order(lower(title) asc)
export type SPONSORS_QUERY_RESULT = Array<{
  _id: string;
  _type: "sponsor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
}>;

// Source: ../src/queries/index.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event"] | order(startDate desc)
export type EVENTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  startDate?: string;
  logo?: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  cover?: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  sections?: PageBuilder;
  seo?: Seo;
}>;

// Source: ../src/queries/layout.ts
// Variable: LAYOUT_QUERY
// Query: *[_type == "siteSettings"][0] {    siteName,    navbar {      ...,      links[] {        label,        "slug": link->slug.current      }    },    footer,    globalSeo  }
export type LAYOUT_QUERY_RESULT = {
  siteName: string | null;
  navbar: {
    _type: "navbar";
    logo?: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    links: Array<{
      label: string | null;
      slug: string | null;
    }> | null;
  } | null;
  footer: Footer | null;
  globalSeo: {
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  } | null;
} | null;

// Source: ../src/queries/notFound.ts
// Variable: NOT_FOUND_QUERY
// Query: *[_type == "notFoundPage"][0]
export type NOT_FOUND_QUERY_RESULT = {
  _id: string;
  _type: "notFoundPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subtitle?: string;
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  backButtonLabel?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    _type: "image";
  };
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"page\" && _id == $id][0] { slug }": INTERNAL_LINK_QUERY_RESULT;
    "*[_type == \"siteSettings\"][0] {\n  indexPage->\n}": INDEX_QUERY_RESULT;
    "*[_type == \"page\" && slug.current == $slug][0]": PAGE_QUERY_RESULT;
    "*[_type == \"event\" && slug.current == $slug][0]": EVENT_PAGE_QUERY_RESULT;
    "*[_type == \"sponsor\"] | order(lower(title) asc)": SPONSORS_QUERY_RESULT;
    "*[_type == \"event\"] | order(startDate desc)": EVENTS_QUERY_RESULT;
    "*[_type == \"siteSettings\"][0] {\n    siteName,\n    navbar {\n      ...,\n      links[] {\n        label,\n        \"slug\": link->slug.current\n      }\n    },\n    footer,\n    globalSeo\n  }": LAYOUT_QUERY_RESULT;
    "*[_type == \"notFoundPage\"][0]": NOT_FOUND_QUERY_RESULT;
  }
}

